apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls-secret
  namespace: default
spec:
  secretName: wildcard-tls-secret
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.${domain}"
