externalIPs:
  enabled: true
gatewayAPI:
  enabled: true
kubeProxyReplacement: true
l2announcements:
  enabled: true
k8sServiceHost: "${kubernetes_hostname}"
k8sServicePort: 6443
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 172.16.0.0/16
