- name: get kubectl from control plane
  hosts: control_planes
  become: true
  tasks:
    - name: Copy kubeadm config to local user
      ansible.builtin.fetch:
        src: "/home/{{ ansible_user }}/.kube/config"
        dest: "{{ lookup('env', 'HOME') }}/.kube/config"
        flat: true
        mode: "0644"
        fail_on_missing: true
      become: false
      when:
        - inventory_hostname == groups['control_planes'][0]
